//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialProduct = new HashSet<MaterialProduct>();
        }
    
        public int MaterialId { get; set; }
        public string MaterialName { get; set; }
        public int MaterialTypeId { get; set; }
        public double MaterialUnitPrice { get; set; }
        public double MaterialQuanityInStock { get; set; }
        public double MaterialMinQuantity { get; set; }
        public double MaterialQuantityInPack { get; set; }
        public int MaterialMeasUnitId { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual MeasUnit MeasUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProduct> MaterialProduct { get; set; }

        [NotMapped]
        public double AmountNeeded { get; set; }
    }
}
